### ISSUE TITLE
Fix failing CLI params/config

### ISSUE THREAD

**Issue by hseabolt** [hseabolt/tautyping#1]
### Description of the bug

Need to update the `params` to reflect the correct CLI options/parameters and not the nf-core boilerplate defaults.

**Comment by srusher** [comment]
Current working command with complete params:

nextflow main.nf --input /scicomp/home-pure/rtq0/Bio/hackathon/tautyping-nf/assets/samplesheet.csv --outdir /scicomp/home-pure/rtq0/Bio/hackathon/tmp --genome GRCh37 -profile conda --kraken2_db /scicomp/home-pure/rtq0/Bio/hackathon/tautyping-nf/assets/kraken --augustus_species galdieria --fasta /scicomp/home-pure/rtq0/Bio/hackathon/tautyping-nf/tmp/Giardia_genomic.fasta
